// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvqshkocijvmqddvlgpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2cXNoa29jaWp2bXFkZHZsZ3BhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDgwNTMsImV4cCI6MjA2Nzg4NDA1M30.Y90aGMcL6ImpUhlcB9jul-89yIFBJ2MpB3YD7EnfnD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});